#!/usr/bin/env python3
"""
Adds search metadata to rendered HTML documents and writes docs/sitemap.xml.

Runs *after* pandoc, never as an --include-in-header: pandoc's
--embed-resources fetches and inlines the target of any <link href> it finds, so
a canonical URL added before the render comes out with its href stripped and the
fetched page embedded in the file. Meta tags and inline JSON-LD survive the
render untouched, but the canonical has to be added here.

Page title and description are read back out of the rendered HTML — pandoc
writes them from each document's YAML front matter — so this script holds no
per-document metadata of its own to drift out of sync. The share card it links
as og:image is drawn beforehand by og_cards.py.

Usage:
    python3 inject_seo.py <docs-dir> --site-url <url> [--repo-root <path>]
"""

from __future__ import annotations

import argparse
import hashlib
import html
import json
import pathlib
import re
import struct
import subprocess
import sys
from datetime import date

SENTINEL_BEGIN = "<!-- seo:begin (generated by scripts/inject_seo.py) -->"
SENTINEL_END = "<!-- seo:end -->"

SITE_NAME = "Quant Research"
AUTHOR = "Robert Mahfoud"
LICENSE_URL = "https://creativecommons.org/publicdomain/zero/1.0/"

TITLE_RE = re.compile(r"<title>(.*?)</title>", re.DOTALL)
DESCRIPTION_RE = re.compile(r'<meta\s+name="description"\s+content="(.*?)"\s*/?>', re.DOTALL)
PANDOC_RE = re.compile(r'<meta\s+name="generator"\s+content="pandoc')
SENTINEL_RE = re.compile(re.escape(SENTINEL_BEGIN) + r".*?" + re.escape(SENTINEL_END), re.DOTALL)


def git_dates(path: pathlib.Path, repo_root: pathlib.Path) -> tuple[str, str]:
    """(first commit date, last commit date) for a file, falling back to mtime."""

    def log(*args: str) -> list[str]:
        try:
            result = subprocess.run(
                ["git", "-C", str(repo_root), "log", *args, "--format=%cs", "--", str(path)],
                capture_output=True,
                text=True,
                check=True,
            )
        except (subprocess.CalledProcessError, FileNotFoundError):
            return []
        return result.stdout.split()

    mtime = date.fromtimestamp(path.stat().st_mtime).isoformat() if path.exists() else date.today().isoformat()
    reversed_log = log("--reverse")
    latest = log("-1")
    return (reversed_log[0] if reversed_log else mtime, latest[0] if latest else mtime)


def read_meta(markup: str) -> tuple[str | None, str | None]:
    title = TITLE_RE.search(markup)
    description = DESCRIPTION_RE.search(markup)
    return (
        html.unescape(title.group(1)).strip() if title else None,
        html.unescape(description.group(1)).strip() if description else None,
    )


def strip_site_suffix(title: str) -> str:
    """Drop a trailing site name: og:site_name carries it separately."""
    for separator in (" — ", " – ", " | ", " - "):
        head, sep, tail = title.rpartition(separator)
        if sep and tail.strip() == SITE_NAME:
            return head.strip()
    return title


def attr(value: str) -> str:
    return html.escape(value, quote=True)


def share_card(docs_dir: pathlib.Path, site_url: str, slug: str) -> tuple[str, int, int] | None:
    """
    (URL, width, height) of the page's share card from og_cards.py, if drawn.

    The URL carries a content hash: platforms cache images by URL, so a card
    redrawn after a title change would otherwise keep showing the old one.
    """
    for candidate in (f"og/{slug}.png", "og/default.png"):
        path = docs_dir / candidate
        if path.exists():
            data = path.read_bytes()
            width, height = struct.unpack(">II", data[16:24])  # PNG IHDR
            return f"{site_url}{candidate}?v={hashlib.sha256(data).hexdigest()[:10]}", width, height
    return None


def build_block(
    *,
    slug: str,
    title: str,
    description: str,
    site_url: str,
    docs_dir: pathlib.Path,
    published: str,
    modified: str,
) -> str:
    canonical = f"{site_url}{slug}.html"
    headline = strip_site_suffix(title)
    image = share_card(docs_dir, site_url, slug)

    lines = [
        SENTINEL_BEGIN,
        f'<link rel="canonical" href="{attr(canonical)}" />',
    ]
    if (docs_dir / f"{slug}.pdf").exists():
        lines.append(f'<link rel="alternate" type="application/pdf" href="{attr(slug)}.pdf" />')

    lines += [
        '<meta property="og:type" content="article" />',
        f'<meta property="og:site_name" content="{attr(SITE_NAME)}" />',
        f'<meta property="og:title" content="{attr(headline)}" />',
        f'<meta property="og:description" content="{attr(description)}" />',
        f'<meta property="og:url" content="{attr(canonical)}" />',
        '<meta property="og:locale" content="en_US" />',
        f'<meta property="article:published_time" content="{attr(published)}" />',
        f'<meta property="article:modified_time" content="{attr(modified)}" />',
        f'<meta name="twitter:card" content="{"summary_large_image" if image else "summary"}" />',
        f'<meta name="twitter:title" content="{attr(headline)}" />',
        f'<meta name="twitter:description" content="{attr(description)}" />',
    ]
    if image:
        image_url, width, height = image
        lines += [
            f'<meta property="og:image" content="{attr(image_url)}" />',
            '<meta property="og:image:type" content="image/png" />',
            f'<meta property="og:image:width" content="{width}" />',
            f'<meta property="og:image:height" content="{height}" />',
            f'<meta property="og:image:alt" content="{attr(headline)}" />',
            f'<meta name="twitter:image" content="{attr(image_url)}" />',
            f'<meta name="twitter:image:alt" content="{attr(headline)}" />',
        ]

    article = {
        "@context": "https://schema.org",
        "@type": "TechArticle",
        "headline": headline,
        "description": description,
        "url": canonical,
        "mainEntityOfPage": {"@type": "WebPage", "@id": canonical},
        "author": {"@type": "Person", "name": AUTHOR},
        "publisher": {"@type": "Person", "name": AUTHOR},
        "datePublished": published,
        "dateModified": modified,
        "inLanguage": "en",
        "license": LICENSE_URL,
        "isPartOf": {"@type": "CollectionPage", "name": SITE_NAME, "url": site_url},
    }
    if image:
        image_url, width, height = image
        article["image"] = {"@type": "ImageObject", "url": image_url, "width": width, "height": height}

    breadcrumbs = {
        "@context": "https://schema.org",
        "@type": "BreadcrumbList",
        "itemListElement": [
            {"@type": "ListItem", "position": 1, "name": SITE_NAME, "item": site_url},
            {"@type": "ListItem", "position": 2, "name": headline, "item": canonical},
        ],
    }

    for payload in (article, breadcrumbs):
        lines.append('<script type="application/ld+json">')
        lines.append(json.dumps(payload, ensure_ascii=False, indent=2))
        lines.append("</script>")

    lines.append(SENTINEL_END)
    return "\n".join(lines)


def inject(markup: str, block: str) -> str | None:
    if SENTINEL_RE.search(markup):
        return SENTINEL_RE.sub(lambda _: block, markup, count=1)
    match = TITLE_RE.search(markup)
    if not match:
        return None
    end = match.end()
    return markup[:end] + "\n" + block + markup[end:]


def write_sitemap(docs_dir: pathlib.Path, site_url: str, entries: list[tuple[str, str]]) -> pathlib.Path:
    urls = [f"  <url>\n    <loc>{site_url}</loc>\n    <lastmod>{max(m for _, m in entries)}</lastmod>\n  </url>"]
    for slug, modified in sorted(entries):
        loc = html.escape(f"{site_url}{slug}.html", quote=False)
        urls.append(f"  <url>\n    <loc>{loc}</loc>\n    <lastmod>{modified}</lastmod>\n  </url>")

    out = docs_dir / "sitemap.xml"
    out.write_text(
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n' + "\n".join(urls) + "\n</urlset>\n",
        encoding="utf-8",
    )
    return out


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("docs_dir", type=pathlib.Path)
    parser.add_argument("--site-url", required=True)
    parser.add_argument("--repo-root", type=pathlib.Path, default=pathlib.Path("."))
    parser.add_argument(
        "--require",
        action="append",
        default=[],
        metavar="SLUG",
        help="fail if this page lacks metadata; other pages only warn (they may be stale renders)",
    )
    args = parser.parse_args()

    # Resolved, because git_dates pathspecs are matched against the repo root:
    # a relative path silently matches nothing and dates fall back to mtime.
    docs_dir: pathlib.Path = args.docs_dir.resolve()
    site_url = args.site_url if args.site_url.endswith("/") else args.site_url + "/"
    source_dir = docs_dir.parent

    if not docs_dir.is_dir():
        print(f"{docs_dir}: no such directory", file=sys.stderr)
        return 1

    entries: list[tuple[str, str]] = []
    errors = 0
    required = set(args.require)

    def complain(slug: str, message: str) -> None:
        nonlocal errors
        if slug in required or not required:
            errors += 1
            print(f"✗ {slug}.html: {message}", file=sys.stderr)
        else:
            print(f"! {slug}.html: {message} (stale render)", file=sys.stderr)

    for page in sorted(docs_dir.glob("*.html")):
        markup = page.read_text(encoding="utf-8")
        if not PANDOC_RE.search(markup):
            continue  # index.html and anything else hand-maintained

        slug = page.stem
        title, description = read_meta(markup)
        if not title or title == slug:
            complain(slug, f"no page title — add `pagetitle:` to {slug}.md front matter")
            continue
        if not description:
            complain(slug, f"no description — add `description:` to {slug}.md front matter")
            continue

        published, modified = git_dates(source_dir / f"{slug}.md", args.repo_root)
        block = build_block(
            slug=slug,
            title=title,
            description=description,
            site_url=site_url,
            docs_dir=docs_dir,
            published=published,
            modified=modified,
        )
        updated = inject(markup, block)
        if updated is None:
            complain(slug, "no <title> to anchor the metadata block")
            continue

        if updated != markup:
            page.write_text(updated, encoding="utf-8")
        entries.append((slug, modified))

    if entries:
        sitemap = write_sitemap(docs_dir, site_url, entries)
        print(f"✅ search metadata: {len(entries)} page(s), {sitemap.parent.name}/{sitemap.name}")

    return 1 if errors else 0


if __name__ == "__main__":
    sys.exit(main())
